// Country list (Dutch names) — ports COUNTRIES (osago-bundle.js:3373-3399),
// verbatim order (NL/BE/DE/EU favourites first, then alphabetical).
export const COUNTRIES: readonly string[] = [
  'Nederland',
  'België',
  'Duitsland',
  'Frankrijk',
  'Verenigd Koninkrijk',
  'Luxemburg',
  'Oostenrijk',
  'Spanje',
  'Italië',
  'Zwitserland',
  'Afghanistan',
  'Albanië',
  'Algerije',
  'Andorra',
  'Angola',
  'Antigua en Barbuda',
  'Argentinië',
  'Armenië',
  'Aruba',
  'Australië',
  'Azerbeidzjan',
  'Bahama’s',
  'Bahrein',
  'Bangladesh',
  'Barbados',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnië en Herzegovina',
  'Botswana',
  'Brazilië',
  'Brunei',
  'Bulgarije',
  'Burkina Faso',
  'Burundi',
  'Cambodja',
  'Canada',
  'Chili',
  'China',
  'Colombia',
  'Comoren',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Denemarken',
  'Djibouti',
  'Dominica',
  'Dominicaanse Republiek',
  'Ecuador',
  'Egypte',
  'El Salvador',
  'Equatoriaal-Guinea',
  'Eritrea',
  'Estland',
  'Eswatini',
  'Ethiopië',
  'Fiji',
  'Filipijnen',
  'Finland',
  'Gabon',
  'Gambia',
  'Georgië',
  'Ghana',
  'Grenada',
  'Griekenland',
  'Guatemala',
  'Guinee',
  'Guinee-Bissau',
  'Guyana',
  'Haïti',
  'Honduras',
  'Hongarije',
  'Ierland',
  'IJsland',
  'India',
  'Indonesië',
  'Irak',
  'Iran',
  'Israël',
  'Ivoorkust',
  'Jamaica',
  'Japan',
  'Jemen',
  'Jordanië',
  'Kaapverdië',
  'Kameroen',
  'Kazachstan',
  'Kenia',
  'Kirgizië',
  'Kiribati',
  'Koeweit',
  'Kosovo',
  'Kroatië',
  'Laos',
  'Lesotho',
  'Letland',
  'Libanon',
  'Liberia',
  'Libië',
  'Liechtenstein',
  'Litouwen',
  'Madagaskar',
  'Malawi',
  'Maldiven',
  'Maleisië',
  'Mali',
  'Malta',
  'Marokko',
  'Marshalleilanden',
  'Mauritanië',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldavië',
  'Monaco',
  'Mongolië',
  'Montenegro',
  'Mozambique',
  'Myanmar',
  'Namibië',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Noord-Korea',
  'Noord-Macedonië',
  'Noorwegen',
  'Nieuw-Zeeland',
  'Oeganda',
  'Oekraïne',
  'Oezbekistan',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papoea-Nieuw-Guinea',
  'Paraguay',
  'Peru',
  'Polen',
  'Portugal',
  'Qatar',
  'Roemenië',
  'Rusland',
  'Rwanda',
  'Saint Kitts en Nevis',
  'Saint Lucia',
  'Saint Vincent en de Grenadines',
  'Salomonseilanden',
  'Samoa',
  'San Marino',
  'Sao Tomé en Principe',
  'Saoedi-Arabië',
  'Senegal',
  'Servië',
  'Seychellen',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovenië',
  'Slowakije',
  'Soedan',
  'Somalië',
  'Sri Lanka',
  'Suriname',
  'Syrië',
  'Tadzjikistan',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad en Tobago',
  'Tsjaad',
  'Tsjechië',
  'Tunesië',
  'Turkije',
  'Turkmenistan',
  'Tuvalu',
  'Uruguay',
  'Vanuatu',
  'Vaticaanstad',
  'Venezuela',
  'Verenigde Arabische Emiraten',
  'Verenigde Staten',
  'Vietnam',
  'Wit-Rusland',
  'Zambia',
  'Zimbabwe',
  'Zuid-Afrika',
  'Zuid-Korea',
  'Zuid-Soedan',
  'Zweden',
]

export const DEFAULT_COUNTRY = 'Nederland'
